<?php

namespace Sportnetzwerk\SpnBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;
use Sportnetzwerk\SpnBundle\Entity\Player;

/**
 * PlayerEventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerEventsRepository extends EntityRepository
{
     public function getEventToken (Player $player, $eventId){
        $token = array();
        $qb = $this->createQueryBuilder('ple')
                ->andWhere('ple.player = ?1')
                ->andWhere('ple.event = ?2')
                ->setParameters(array(1 => $player->getId(), 2 => $eventId));
        $token = $qb->getQuery()->getResult();

        return $token[0]->getToken();
    }
    
    public function getPlayerEvents(Player $player){
        $events = $this->findByPlayer($player->getId());
        return $events;
    }
    
    /**
     * Returns the count of all participating players per event
     */
    public function getEventPlayers($eventId){
        $pleventsEntries = $this->findByEvent($eventId);
        return count($pleventsEntries);
    }
    
    /**
     * Return participating player names per event
     */
    public function getEventPlayersNames($eventId){
        $pleventsEntries = $this->findByEvent($eventId);
        foreach( $pleventsEntries as $entry ){
            $player[] = $entry->getPlayer()->getName();
        }
        return $player;
    }
}
